#!/bin/bash

GOOS=linux go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o mutating-webhook .

docker build -t 217386048230.dkr.ecr.us-east-1.amazonaws.com/analytics-spark-injector:0.0.1 .
